version: "3.7"

services:
  app_proxy:
    environment:
      APP_HOST: myspeed_web_1
      APP_PORT: 5216

  web:
    image: germannewsmaker/myspeed
    # myspeed must be run as root
    restart: on-failure
    stop_grace_period: 1m
    volumes:
     - ${APP_DATA_DIR}/data/myspeed:/myspeed/data
