
services:
  app_proxy:
    environment:
      APP_HOST: $APP_ELECTRUMX_IP
      APP_PORT: 3007

  app:
    depends_on:
      - electrumx
    restart: on-failure
    environment:
      ELECTRUM_HIDDEN_SERVICE: "${APP_HIDDEN_SERVICE}"
      ELECTRUM_LOCAL_SERVICE: "${DEVICE_DOMAIN_NAME}"
      ELECTRUM_HOST: "${APP_ELECTRUMX_NODE_IP}"
      BITCOIN_HOST: "${APP_BITCOIN_NODE_IP}"
      RPC_USER: "${APP_BITCOIN_RPC_USER}"
      RPC_PASSWORD: "${APP_BITCOIN_RPC_PASS}"
    networks:
      default:
        ipv4_address: $APP_ELECTRUMX_IP
  
  electrumx:
    image: lukechilds/electrumx
    init: true
    environment:
      DAEMON_URL: "http://${APP_BITCOIN_RPC_USER}:${APP_BITCOIN_RPC_PASS}@${APP_BITCOIN_NODE_IP}:${APP_BITCOIN_RPC_PORT}"
      COIN: BitcoinSegwit
      NET: "${APP_BITCOIN_NETWORK}"
    volumes:
      - ${APP_DATA_DIR}/data:/data
    restart: always
    networks:
      default:
        ipv4_address: $APP_ELECTRUMX_NODE_IP
