version: "1.0"

services:
  app_proxy:
    environment:
      # Formato: <app-id>_<docker-service-name>_1
      APP_HOST: btcinoutalert-fulcrum
      APP_PORT: 3000

  server:
    image: getumbrel/community-app-store-fulcrum:latest
    user: "1000:1000"
    init: true

  fulcrum-mainnet:
    build: .
    dockerfile: Dockerfile
    container_name: fulcrum-mainnet
    volumes:
      - /home/umbrel/umbrel/app-data/bitcoin:/home/umbrel/appdata/fulcrum
    ports:
      - "50001:50001"
      - "50002:50002"
    restart: always
